<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.catools</groupId>
    <artifactId>pipeline</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>Core Automation Toolset - Pipeline Root</name>
    <description>The Pipeline tools to be used in CATs projects</description>

    <properties>
        <revision>2.0.0-SNAPSHOT</revision>
        <maven.deploy.skip>true</maven.deploy.skip>
        <spotless.skip>true</spotless.skip>
    </properties>

    <modules>
        <module>athena</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>catools.parent</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
