<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>mcp.server</artifactId>
    <packaging>jar</packaging>

    <name>MCP Toolset - MCP Server</name>
    <description>The MCP Server to be used in CATs projects</description>

    <parent>
        <groupId>org.catools</groupId>
        <artifactId>mcp.parent</artifactId>
        <version>${revision}</version>
        <relativePath>../mcp.parent/pom.xml</relativePath>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.catools</groupId>
            <artifactId>mcp.core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.modelcontextprotocol.sdk</groupId>
            <artifactId>mcp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.ee10</groupId>
            <artifactId>jetty-ee10-servlet</artifactId>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.failsafe</groupId>
            <artifactId>failsafe</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
