<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.catools</groupId>
    <artifactId>common</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>Core Automation Common - Root</name>
    <description>The common objects which use in all other CATools projects</description>

    <properties>
        <revision>2.0.0-SNAPSHOT</revision>
        <maven.deploy.skip>true</maven.deploy.skip>
        <spotless.skip>true</spotless.skip>
    </properties>

    <modules>
        <module>common.concurrent</module>
        <module>common.extension</module>
        <module>common.faker</module>
        <module>common.logger</module>
        <module>common.poi</module>
        <module>common.sql</module>
        <module>common.metrics</module>
        <module>common.security</module>
        <module>common.testng</module>
        <module>common.utils</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>parent</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.extension</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.utils</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.logger</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.concurrent</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.testng</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.faker</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.poi</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.metrics</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>common.sql</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
