name: CATools CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --allow-secret-key-import --import
          echo "$GPG_PUBLIC_KEY" | gpg --import
          export MAVEN_OPTS="-DCATOOLS_WEB_GRID_USE_TEST_CONTAINER=true -DCATOOLS_LOGGER_CONSOLE_LOG_LEVEL=WARN"
          ./mvnw -B verify -P release org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=catools2_CATools $MAVEN_OPTS

      - name: Deploying to GitHub
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --allow-secret-key-import --import
          echo "$GPG_PUBLIC_KEY" | gpg --import
          ./mvnw org.codehaus.mojo:versions-maven-plugin:2.15.0:set-property -Dproperty=revision -DnewVersion=$GITHUB_REF_NAME -q
          ./mvnw deploy -P release -DskipTests
