package org.catools.mcp.enums;

/**
 * Created by amogyla on 5/4/2016.
 */
public enum Country {
    // select * from country order by 1 asc;
    AD("Andorra"),
    AE("United Arab Emirates"),
    AF("Afghanistan"),
    AG("Antigua & Barbuda"),
    AI("Anguilla"),
    AL("Albania"),
    AM("Armenia"),
    AN("Netherlands Antilles"),
    AO("Angola"),
    AQ("Antarctica"),
    AR("Argentina"),
    AS("American Samoa"),
    AT("Austria"),
    AU("Australia"),
    AW("Aruba"),
    AX("ALAND ISLANDS"),
    AZ("Azerbaijan"),
    BA("Bosnia & Herzegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Belgium"),
    BF("Burkina Faso"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BI("Burundi"),
    BJ("Benin"),
    BL("SAINT BARTHELEMY"),
    BM("Bermuda"),
    BN("Brunei Darussalam"),
    BO("Bolivia"),
    BQ("BONAIRE, SINT EUSTATIUS AND SABA"),
    BR("Brazil"),
    BS("Bahamas"),
    BT("Bhutan"),
    BV("Bouvet Island"),
    BW("Botswana"),
    BY("Belarus"),
    BZ("Belize"),
    CA("Canada"),
    CC("Cocos (Keeling) Islands"),
    CD("Democratic Republic of the Congo"),
    CF("Central African Republic"),
    CG("Congo"),
    CH("Switzerland"),
    CI("Cote D'ivoire (Ivory Coast)"),
    CK("Cook Islands"),
    CL("Chile"),
    CM("Cameroon"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    CU("Cuba"),
    CV("Cape Verde"),
    CW("CURACAO"),
    CX("Christmas Island"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DE("Germany"),
    DJ("Djibouti"),
    DK("Denmark"),
    DM("Dominica"),
    DO("Dominican Republic"),
    DZ("Algeria"),
    EC("Ecuador"),
    EE("Estonia"),
    EG("Egypt"),
    EH("Western Sahara"),
    ER("Eritrea"),
    ES("Spain"),
    ET("Ethiopia"),
    FI("Finland"),
    FJ("Fiji"),
    FK("Falkland Islands (Malvinas)"),
    FM("Micronesia"),
    FO("Faroe Islands"),
    FR("France"),
    GA("Gabon"),
    GB("United Kingdom"),
    GD("Grenada"),
    GE("Georgia"),
    GF("French Guiana"),
    GG("GUERNSEY"),
    GH("Ghana"),
    GI("Gibraltar"),
    GL("Greenland"),
    GM("Gambia"),
    GN("Guinea"),
    GP("Guadeloupe"),
    GQ("Equatorial Guinea"),
    GR("Greece"),
    GS("S.Georgia & S.Sandwich Islands"),
    GT("Guatemala"),
    GU("Guam"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hong Kong"),
    HM("Heard & McDonald Islands"),
    HN("Honduras"),
    HR("Croatia (Hrvatska)"),
    HT("Haiti"),
    HU("Hungary"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IM("ISLE OF MAN"),
    IN("India"),
    IO("British Indian Ocean Territory"),
    IQ("Iraq"),
    IR("Iran"),
    IS("Iceland"),
    IT("Italy"),
    JE("JERSEY"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kyrgyzstan"),
    KH("Cambodia"),
    KI("Kiribati"),
    KM("Comoros"),
    KN("Saint Kitts & Nevis"),
    KP("Korea (North)"),
    KR("Korea (South)"),
    KW("Kuwait"),
    KY("Cayman Islands"),
    KZ("Kazakhstan"),
    LA("Laos"),
    LB("Lebanon"),
    LC("Saint Lucia"),
    LI("Liechtenstein"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesotho"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libya"),
    MA("Morocco"),
    MC("Monaco"),
    MD("Moldova"),
    ME("MONTENEGRO"),
    MF("SAINT MARTIN (FRENCH PART)"),
    MG("Madagascar"),
    MH("Marshall Islands"),
    MK("Macedonia"),
    ML("Mali"),
    MM("MYANMAR"),
    MN("Mongolia"),
    MO("Macau"),
    MP("Northern Mariana Islands"),
    MQ("Martinique"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU("Mauritius"),
    MV("Maldives"),
    MW("Malawi"),
    MX("Mexico"),
    MY("Malaysia"),
    MZ("Mozambique"),
    NA("Namibia"),
    NC("New Caledonia"),
    NE("Niger"),
    NF("Norfolk Island"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Netherlands"),
    NO("Norway"),
    NP("Nepal"),
    NR("Nauru"),
    NU("Niue"),
    NZ("New Zealand"),
    OM("Oman"),
    PA("Panama"),
    PE("Peru"),
    PF("French Polynesia"),
    PG("Papua New Guinea"),
    PH("Philippines"),
    PK("Pakistan"),
    PL("Poland"),
    PM("St. Pierre & Miquelon"),
    PN("Pitcairn"),
    PR("Puerto Rico"),
    PS("PALESTINIAN TERRITORY, OCCUPIED"),
    PT("Portugal"),
    PW("Palau"),
    PY("Paraguay"),
    QA("Qatar"),
    RE("Reunion"),
    RO("Romania"),
    RS("SERBIA"),
    RU("Russian Federation"),
    RW("Rwanda"),
    SA("Saudi Arabia"),
    SB("Solomon Islands"),
    SC("Seychelles"),
    SD("Sudan"),
    SE("Sweden"),
    SG("Singapore"),
    SH("St. Helena"),
    SI("Slovenia"),
    SJ("Svalbard & Jan Mayen Islands"),
    SK("Slovak Republic"),
    SL("Sierra Leone"),
    SM("San Marino"),
    SN("Senegal"),
    SO("Somalia"),
    SR("Suriname"),
    SS("SOUTH SUDAN"),
    ST("Sao Tome & Principe"),
    SV("El Salvador"),
    SX("SINT MAARTEN (DUTCH PART)"),
    SY("Syria"),
    SZ("Swaziland"),
    TC("Turks & Caicos Islands"),
    TD("Chad"),
    TF("French Southern Territories"),
    TG("Togo"),
    TH("Thailand"),
    TJ("Tajikistan"),
    TK("Tokelau"),
    TL("TIMOR-LESTE"),
    TM("Turkmenistan"),
    TN("Tunisia"),
    TO("Tonga"),
    TP("East Timor"),
    TR("Turkey"),
    TV("Tuvalu"),
    TW("Taiwan"),
    TZ("Tanzania"),
    UA("Ukraine"),
    UG("Uganda"),
    UM("US MINOR OUTLYING ISLANDS"),
    US("United States"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VA("Vatican City (Holy See)"),
    VC("St. Vincent & the Grenadines"),
    VE("Venezuela"),
    VG("Virgin Islands (British)"),
    VI("Virgin Islands (U.S.)"),
    VN("Viet Nam"),
    VU("Vanuatu"),
    WF("Wallis & Futuna Islands"),
    WS("Samoa"),
    YE("Yemen"),
    YT("Mayotte"),
    ZA("South Africa"),
    ZM("Zambia"),
    ZW("Zimbabwe"),
    PRESQUE_ISLE("Presque Isle");

    private String fullName;

    Country(String fullName) {
        this.fullName = fullName;
    }

}
